allowBuilds:
  '@parcel/watcher': true
  '@swc/core': true
  core-js: true
  sharp: true
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
minimumReleaseAgeExclude:
  - '@omnixys/contracts@2.0.1'
