"use client";

import { TimelineItem } from "@/checkpoint/components/event/settings/sections/TimelineSection";
import { Button, useTheme } from "@mui/material";
import { alpha } from "@mui/material/styles";
import dayjs from "dayjs";

/**
 * TimelineExport
 *
 * Responsibilities:
 * - Generates a print-ready timeline document
 * - Opens in new window (better UX than forced download)
 * - Uses clean, branded layout
 *
 * Notes:
 * - Optimized for A4 printing
 * - Uses minimal inline CSS for maximum compatibility
 */
export default function TimelineExport({ items }: { items: TimelineItem[] }) {
  const theme = useTheme();

  const handleDownload = () => {
    const sorted = [...items].sort(
      (a, b) => new Date(a.timestamp).getTime() - new Date(b.timestamp).getTime(),
    );

    const html = `
      <html>
        <head>
          <title>Timeline</title>

          <style>
            @page {
              size: A4;
              margin: 30mm 20mm;
            }

            body {
              font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif;
              color: #1a1a1a;
              background: #ffffff;
            }

            .container {
              max-width: 800px;
              margin: 0 auto;
            }

            .header {
              text-align: center;
              margin-bottom: 40px;
            }

            .title {
              font-size: 28px;
              font-weight: 600;
              letter-spacing: 0.04em;
            }

            .subtitle {
              font-size: 14px;
              color: #888;
              margin-top: 6px;
            }

            .timeline {
              margin-top: 20px;
            }

            .item {
              display: flex;
              justify-content: space-between;
              align-items: center;
              padding: 14px 0;
              border-bottom: 1px solid #eee;
            }

            .label {
              font-size: 16px;
              font-weight: 500;
            }

            .time {
              font-size: 14px;
              font-weight: 600;
              color: #999;
              letter-spacing: 0.05em;
            }

            .footer {
              margin-top: 50px;
              text-align: center;
              font-size: 12px;
              color: #aaa;
            }
          </style>
        </head>

        <body>
          <div class="container">

            <div class="header">
              <div class="title">Event Timeline</div>
              <div class="subtitle">${dayjs().format("DD MMMM YYYY")}</div>
            </div>

            <div class="timeline">
              ${sorted
                .map(
                  (i) => `
                  <div class="item">
                    <div class="label">${i.label}</div>
                    <div class="time">${dayjs(i.timestamp).format("HH:mm")}</div>
                  </div>
                `,
                )
                .join("")}
            </div>

            <div class="footer">
              Generated by Omnixys
            </div>

          </div>
        </body>
      </html>
    `;

    const newWindow = window.open("", "_blank");

    if (!newWindow) return;

    newWindow.document.write(html);
    newWindow.document.close();

    // optional auto-print
    newWindow.focus();
    newWindow.print();
  };

  return (
    <Button
      onClick={handleDownload}
      fullWidth
      sx={{
        mt: 3,
        py: 1.8,
        borderRadius: 4,
        fontWeight: 700,
        fontSize: "1rem",
        letterSpacing: "0.05em",

        background: `linear-gradient(135deg,
          ${theme.palette.primary.main},
          ${theme.palette.secondary.main}
        )`,

        boxShadow: `0 12px 30px ${alpha(theme.palette.primary.main, 0.4)}`,

        color: "#fff",

        "&:hover": {
          transform: "translateY(-2px)",
          boxShadow: `0 18px 45px ${alpha(theme.palette.primary.main, 0.6)}`,
        },
      }}
    >
      ✨ Download & Print Timeline
    </Button>
  );
}
