query GetEventTree($eventId: ID!) {
  eventTree(eventId: $eventId) {
    rootEvent {
      id
      name
      settings {
        id
        endsAt
        invitedByOptions
      }
    }
    subEvents {
      id
      name
      parentId
      depth
      settings {
        id
        endsAt
        invitedByOptions
      }
    }
  }
}

query GetPublicEventTree($eventId: ID!) {
  publicEventTree(eventId: $eventId) {
    rootEvent {
      id
      name
      settings {
        id
        endsAt
        invitedByOptions
      }
    }
    subEvents {
      id
      name
      parentId
      depth
      settings {
        id
        endsAt
        invitedByOptions
      }
    }
  }
}

query GetFullEventTreeInfo($eventId: ID!) {
  eventTree(eventId: $eventId) {
    rootEvent {
      id
      name
      settings {
        id
        endsAt
        invitedByOptions
        seatColorGroups {
          id
          name
          matchType
          invitedByValues
          priority
          order
          isOrphaned
          style {
            background
            foreground
            border
            legendIcon
          }
        }
      }
    }
    subEvents {
      id
      name
      settings {
        id
        endsAt
        invitedByOptions
        seatColorGroups {
          id
          name
          matchType
          invitedByValues
          priority
          order
          isOrphaned
          style {
            background
            foreground
            border
            legendIcon
          }
        }
      }
    }
  }
}
