query GetEventTree($eventId: ID!) {
  eventTree(eventId: $eventId) {
    rootEvent {
      id
      name
      settings {
        endsAt
      }
    }
    subEvents {
      id
      name
      parentId
      depth
      settings {
        endsAt
      }
    }
  }
}

query GetPublicEventTree($eventId: ID!) {
  publicEventTree(eventId: $eventId) {
    rootEvent {
      id
      name
      settings {
        endsAt
      }
    }
    subEvents {
      id
      name
      parentId
      depth
      settings {
        endsAt
      }
    }
  }
}

query GetFullEventTreeInfo($eventId: ID!) {
  eventTree(eventId: $eventId) {
    rootEvent {
      id
      name
      settings {
        endsAt
      }
    }
    subEvents {
      id
      name
      settings {
        endsAt
      }
    }
  }
}
