query Event($id: ID!) {
  event(id: $id) {
    ...EventFull
  }
}

query EventPage($eventId: ID!) {
  event(id: $eventId) {
    id
    name
    myRole
    timeline {
      id
      eventId
      referenceId
      sourceId
      type
      timestamp
      label
    }
    coverMedia {
      id
      url
      variants {
        url
        width
      }
    }
    settings {
      startsAt
      endsAt
      dressCode
      description
      category
      approvalMode
      allowPublicRsvp
      allowPublicPlusOne
      allowGuestSeatSelection
      allowPublicRsvpWebsite
      allowPlusOneUpdate
      maxPlusOnes
      requireApprovalForPlusOnes
      rsvpDeadline
      ticketReleaseAt
      isPublic
      publicRsvpWebsite
      visibleTabs
      invitedByOptions
    }
  }
}

query GetEventMeta($eventId: ID!) {
  event(id: $eventId) {
    id
    name
    myRole
    coverMedia {
      id
      url
    }
  }
}

query GetEventName($eventId: ID!) {
  event(id: $eventId) {
    name
  }
}

query GetActiveEvent($eventId: ID!) {
  event(id: $eventId) {
    id
    name
    myRole
    settings {
      allowGuestSeatSelection
      startsAt
      endsAt
      invitedByOptions
      visibleTabs
    }
  }
}

query GetEventSettings($eventId: ID!) {
  event(id: $eventId) {
    id
    name
    myRole
    owner
    parentId
    userRoles {
      role
      userId
    }
    timeline {
      id
      eventId
      referenceId
      sourceId
      type
      timestamp
      label
    }
    coverMedia {
      id
      url
      variants {
        url
        width
      }
    }
    settings {
      id
      allowReEntry
      rotateSeconds
      maxSeats
      dressCode
      description
      isActive
      startsAt
      endsAt
      allowPublicRsvp
      allowPublicPlusOne
      allowPublicRsvpWebsite
      allowPlusOneUpdate
      maxPlusOnes
      requireApprovalForPlusOnes
      rsvpDeadline
      approvalMode
      allowGuestSeatSelection
      allowSeatOverbooking
      isPublic
      publicRsvpWebsite
      visibleTabs
      invitedByOptions
      category
      createdAt
      updatedAt
      ticketReleaseAt
      seatColorGroups {
        id
        name
        matchType
        invitedByValues
        priority
        order
        isOrphaned
        style {
          background
          foreground
          border
          legendIcon
        }
      }
    }
  }
}
