query RsvpSupportConversation(
  $invitationId: String!
  $firstMessage: String!
  $channel: ConversationChannel!
) {
  rsvpSupportConversation(
    invitationId: $invitationId
    firstMessage: $firstMessage
    channel: $channel
  ) {
    conversation {
      ...SupportConversationFields
    }
    messages {
      ...SupportMessageFields
    }
  }
}

query RsvpSupportMessages($invitationId: String!, $limit: Float) {
  rsvpSupportMessages(invitationId: $invitationId, limit: $limit) {
    ...SupportMessageFields
  }
}

mutation RsvpSendSupportMessage($invitationId: String!, $body: String, $mediaUrl: String) {
  rsvpSendSupportMessage(invitationId: $invitationId, body: $body, mediaUrl: $mediaUrl) {
    ...SupportMessageFields
  }
}

mutation RsvpMarkConversationAsRead($invitationId: String!) {
  rsvpMarkConversationAsRead(invitationId: $invitationId) {
    ...SupportConversationFields
  }
}
