"use client";

import {
  Button,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  MenuItem,
  Select,
  Stack,
  TextField,
  Typography,
} from "@mui/material";
import React from "react";
import { SectionShape, TableShape } from "@/checkpoint/generated/schema";
import type { SectionShape as SectionShapeT, TableShape as TableShapeT } from "@/checkpoint/generated/schema";

interface Props {
  open: boolean;
  onClose: () => void;
  onGenerate: (input: {
    sectionName: string;
    seatCount: number;
    tableCount: number;
    tableShape: TableShapeT;
    sectionLayout: SectionShapeT;
    spacing: number;
  }) => void;
}

const TABLE_SHAPES: { value: TableShapeT; label: string }[] = [
  { value: TableShape.ROUND, label: "Rund" },
  { value: TableShape.RECTANGLE, label: "Rechteckig" },
  { value: TableShape.OVAL, label: "Oval" },
  { value: TableShape.ROW, label: "Reihen" },
];

const SECTION_LAYOUTS: { value: SectionShapeT; label: string }[] = [
  { value: SectionShape.RECTANGLE, label: "Rechteckig" },
  { value: SectionShape.CIRCLE, label: "Rund" },
];

export default function SeatMapAutoGenerateDialog({ open, onClose, onGenerate }: Props) {
  const [sectionName, setSectionName] = React.useState("");
  const [seatCount, setSeatCount] = React.useState(50);
  const [tableCount, setTableCount] = React.useState(10);
  const [tableShape, setTableShape] = React.useState<TableShapeT>(TableShape.ROUND);
  const [sectionLayout, setSectionLayout] = React.useState<SectionShapeT>(SectionShape.RECTANGLE);
  const [spacing, setSpacing] = React.useState(20);

  React.useEffect(() => {
    if (open && !sectionName) {
      setSectionName(
        `Auto ${new Date().toLocaleTimeString("de-DE", { hour: "2-digit", minute: "2-digit" })}`,
      );
    }
  }, [open, sectionName]);

  const handleGenerate = () => {
    onGenerate({
      sectionName: sectionName.trim() || `Auto ${Date.now()}`,
      seatCount,
      tableCount,
      tableShape,
      sectionLayout,
      spacing,
    });
  };

  const handleClose = () => {
    onClose();
  };

  return (
    <Dialog open={open} onClose={handleClose} maxWidth="xs" fullWidth={true}>
      <DialogTitle>Sitzplan automatisch generieren</DialogTitle>
      <DialogContent>
        <Stack spacing={2} sx={{ mt: 1 }}>
          <TextField
            label="Bereichsname"
            fullWidth={true}
            value={sectionName}
            onChange={(e) => setSectionName(e.target.value)}
          />

          <TextField
            label="Sitzplätze gesamt"
            type="number"
            fullWidth={true}
            value={seatCount}
            onChange={(e) => setSeatCount(Math.max(1, Number(e.target.value)))}
            slotProps={{ htmlInput: { min: 1 } }}
          />

          <TextField
            label="Tische"
            type="number"
            fullWidth={true}
            value={tableCount}
            onChange={(e) => setTableCount(Math.max(1, Number(e.target.value)))}
            slotProps={{ htmlInput: { min: 1 } }}
          />

          <Stack spacing={0.5}>
            <Typography variant="caption" sx={{ color: "text.secondary" }}>
              Tischform
            </Typography>
            <Select<TableShape>
              fullWidth={true}
              size="small"
              value={tableShape}
              onChange={(e) => setTableShape(e.target.value as TableShape)}
            >
              {TABLE_SHAPES.map((s) => (
                <MenuItem key={s.value} value={s.value}>
                  {s.label}
                </MenuItem>
              ))}
            </Select>
          </Stack>

          <Stack spacing={0.5}>
            <Typography variant="caption" sx={{ color: "text.secondary" }}>
              Bereichs-Layout
            </Typography>
            <Select<SectionShape>
              fullWidth={true}
              size="small"
              value={sectionLayout}
              onChange={(e) => setSectionLayout(e.target.value as SectionShape)}
            >
              {SECTION_LAYOUTS.map((l) => (
                <MenuItem key={l.value} value={l.value}>
                  {l.label}
                </MenuItem>
              ))}
            </Select>
          </Stack>

          <TextField
            label="Abstand zwischen Tischen"
            type="number"
            fullWidth={true}
            value={spacing}
            onChange={(e) => setSpacing(Math.max(0, Number(e.target.value)))}
            slotProps={{ htmlInput: { min: 0 } }}
          />
        </Stack>
      </DialogContent>
      <DialogActions>
        <Button onClick={handleClose}>Abbrechen</Button>
        <Button variant="contained" onClick={handleGenerate}>
          Generieren
        </Button>
      </DialogActions>
    </Dialog>
  );
}
