"use client";
import {
  Alert,
  Box,
  Button,
  CircularProgress,
  Dialog,
  DialogActions,
  DialogContent,
  DialogTitle,
  Tab,
  Tabs,
} from "@mui/material";
import type { ComponentProps } from "react";
import { useEffect, useRef, useState } from "react";
import type { LayoutDocument } from "../core/document";
import SeatMapAutoGenerateDialog from "../SeatMapAutoGenerateDialog";
import { createImportDraft, type LayoutImportDraft } from "./contract";
import { draftIssues, type ImportOperation, importLayoutDraft } from "./domain";
import { ImportReview } from "./ImportReview";
import {
  type ImportSourceKind,
  ImportSourcePanel,
  type PreparedImportSource,
} from "./sources/ImportSourcePanel";
import { analyzeLayoutSource } from "./transport";

interface Props {
  open: boolean;
  onClose: () => void;
  eventId: string;
  document: LayoutDocument;
  onAccept: (operation: ImportOperation) => void;
  presetDisabled: boolean;
  pending?: boolean;
  onGenerate: ComponentProps<typeof SeatMapAutoGenerateDialog>["onGenerate"];
}
export function SeatMapCreateDialog(props: Props) {
  return props.open ? <CreateSession {...props} /> : null;
}
function CreateSession({
  onClose,
  eventId,
  document,
  onAccept,
  presetDisabled,
  pending = false,
  onGenerate,
}: Props) {
  const [tab, setTab] = useState<"PRESET" | ImportSourceKind>(presetDisabled ? "IMAGE" : "PRESET");
  const [source, setSource] = useState<PreparedImportSource | null>(null),
    [draft, setDraft] = useState<LayoutImportDraft | null>(null),
    [busy, setBusy] = useState(false),
    [error, setError] = useState<string | null>(null);
  const request = useRef<AbortController | null>(null);
  useEffect(
    () => () => {
      request.current?.abort();
    },
    [],
  );
  const stop = () => {
    request.current?.abort();
    request.current = null;
    setBusy(false);
  };
  const close = () => {
    stop();
    onClose();
  };
  const analyze = async () => {
    if (!source || busy || pending) return;
    const controller = new AbortController();
    request.current = controller;
    setBusy(true);
    setError(null);
    try {
      const result = await analyzeLayoutSource(eventId, source, controller.signal);
      if (!controller.signal.aborted) setDraft(createImportDraft(result, source.metadata));
    } catch (e) {
      if (!controller.signal.aborted)
        setError(e instanceof Error ? e.message : "Analyse fehlgeschlagen.");
    } finally {
      if (request.current === controller) {
        request.current = null;
        setBusy(false);
      }
    }
  };
  return (
    <Dialog
      open
      onClose={close}
      fullWidth
      maxWidth={draft ? "xl" : "md"}
      aria-labelledby="create-layout-title"
    >
      <DialogTitle id="create-layout-title">Sitzplan erstellen</DialogTitle>
      <Tabs
        value={tab}
        onChange={(_, value) => {
          if (pending) return;
          stop();
          setTab(value);
          setSource(null);
          setDraft(null);
          setError(null);
        }}
        aria-label="Quelle für Sitzplan"
        variant="fullWidth"
      >
        <Tab disabled={pending} value="PRESET" label="Preset" />
        <Tab disabled={pending} value="IMAGE" label="Bild" />
        <Tab disabled={pending} value="PDF" label="PDF" />
        <Tab disabled={pending} value="CAMERA" label="Kamera" />
      </Tabs>
      {tab === "PRESET" ? (
        presetDisabled ? (
          <DialogContent>
            <Alert severity="info">
              Presets verwenden die bestehende Speicherung. Bitte zuerst den lokalen Entwurf
              verwerfen.
            </Alert>
          </DialogContent>
        ) : (
          <SeatMapAutoGenerateDialog
            open
            embedded
            disabled={pending}
            onClose={close}
            onGenerate={onGenerate}
          />
        )
      ) : (
        <>
          <DialogContent dividers>
            <Box sx={{ display: draft ? "none" : "block" }}>
              <ImportSourcePanel
                key={tab}
                kind={tab}
                onPrepared={setSource}
                disabled={busy || pending || Boolean(draft)}
              />
            </Box>
            {draft && source && (
              <ImportReview draft={draft} onChange={setDraft} previewUrl={source.previewUrl} />
            )}
            {busy && (
              <Alert icon={<CircularProgress size={20} />} severity="info">
                Plan wird analysiert …
              </Alert>
            )}
            {error && <Alert severity="error">{error}</Alert>}
          </DialogContent>
          <DialogActions>
            <Button onClick={close}>Abbrechen</Button>
            {busy && <Button onClick={stop}>Analyse abbrechen</Button>}
            {draft ? (
              <>
                <Button
                  onClick={() => {
                    setDraft(null);
                    setError(null);
                  }}
                >
                  Quelle bearbeiten
                </Button>
                <Button
                  variant="contained"
                  disabled={
                    pending ||
                    draftIssues(draft).length > 0 ||
                    !draft.elements.some((e) => !e.excluded)
                  }
                  onClick={() => {
                    try {
                      if (pending) return;
                      onAccept(importLayoutDraft(document, draft));
                      close();
                    } catch (e) {
                      setError(e instanceof Error ? e.message : "Import fehlgeschlagen.");
                    }
                  }}
                >
                  Als lokalen Entwurf übernehmen
                </Button>
              </>
            ) : (
              <Button
                variant="contained"
                disabled={!source || busy || pending}
                onClick={() => void analyze()}
              >
                Plan analysieren
              </Button>
            )}
          </DialogActions>
        </>
      )}
    </Dialog>
  );
}
