/** biome-ignore-all lint/suspicious/noEmptyBlockStatements: kp */
"use client";

import { useMutation, useQuery } from "@apollo/client/react";
import { alpha, Box, Chip, Stack, Typography } from "@mui/material";
import { useParams, useRouter } from "next/navigation";
import React from "react";
import RouteGuard from "@/checkpoint/components/guard/RouteGuard";
import SeatMapAutoGenerateDialog from "@/checkpoint/components/seat/seatMapCanvas/SeatMapAutoGenerateDialog";
import SeatMapCanvas from "@/checkpoint/components/seat/seatMapCanvas/SeatMapCanvas";
import SeatMapEditorToolbar, {
  type EditorMode,
  type SelectedItem,
} from "@/checkpoint/components/seat/seatMapCanvas/SeatMapEditorToolbar";
import SeatMapRenameDialog from "@/checkpoint/components/seat/seatMapCanvas/SeatMapRenameDialog";
import SeatColorLegend from "@/checkpoint/components/seat/seatMapCanvas/SeatColorLegend";
import SeatMapSearch, {
  type SeatMapFilters,
} from "@/checkpoint/components/seat/seatMapCanvas/SeatMapSearch";
import { BackToEventDetailButton } from "@/checkpoint/components/utils/back-to-event-detail-button";
import useEventTreeQuery from "@/checkpoint/hooks/events/useEventTreeQuery";
import {
  AutoGenerateSeatMapDocument,
  CloneSectionDocument,
  CreateSectionDocument,
  CreateTableDocument,
  DeleteSeatDocument,
  DeleteSectionDocument,
  DeleteTableDocument,
  DuplicateTableDocument,
  MoveSeatDocument,
  MoveSectionDocument,
  MoveTableDocument,
  RedoLayoutDocument,
  RenameSectionDocument,
  RenameTableDocument,
  SeatMapViewDocument,
  SectionShape,
  TableShape,
  type SeatMapViewQuery,
  UndoLayoutDocument,
} from "@/checkpoint/generated/graphql";
import useSeatListQuery from "@/checkpoint/hooks/seat/useSeatListQuery";
import { useSeats } from "@/checkpoint/hooks/seat/useSeats";
import { EventPermissionKey } from "@/checkpoint/lib/rbac/event-permissions";
import { useActiveEvent } from "@/checkpoint/providers/ActiveEventProvider";
import { useAuth } from "@/checkpoint/providers/AuthProvider";

function createDefaultSectionName(sections: SeatMapViewQuery["seatLayout"]): string {
  const existing = new Set(sections.map((s) => s.name));
  for (let i = 1; i <= 100; i++) {
    const name = `Section ${i}`;
    if (!existing.has(name)) {
      return name;
    }
  }
  return `Section ${sections.length + 1}`;
}

function createDefaultTableName(tables: { name: string }[]): string {
  const existing = new Set(tables.map((t) => t.name));
  for (let i = 1; i <= 100; i++) {
    const name = `${i}`;
    if (!existing.has(name)) {
      return name;
    }
  }
  return `${tables.length + 1}`;
}

export default function SeatMapClientPage() {
  const { currentUser } = useAuth();
  const { id } = useParams();
  const eventId = id as string;
  const { activeRole, can } = useActiveEvent();
  const router = useRouter();

  const { fullEventTree } = useEventTreeQuery({
    eventId,
    loadFullEventTreeInfo: true,
  });

  const seatColorGroups = React.useMemo(
    () => fullEventTree?.rootEvent?.settings?.seatColorGroups ?? [],
    [fullEventTree],
  );

  const { seatList } = useSeatListQuery({
    eventId,
    loadSeatList: true,
  });

  const { seats, seatListLoading, seatGuestMap, getSeatHolderLabel, getSeatHolderName } =
    useSeats(eventId);

  const {
    data: mapData,
    loading: mapLoading,
    refetch: refetchMap,
  } = useQuery<SeatMapViewQuery>(SeatMapViewDocument, {
    variables: { eventId },
    fetchPolicy: "cache-and-network",
  });

  const [createSection] = useMutation(CreateSectionDocument);
  const [createTable] = useMutation(CreateTableDocument);
  const [deleteSection] = useMutation(DeleteSectionDocument);
  const [deleteTable] = useMutation(DeleteTableDocument);
  const [deleteSeat] = useMutation(DeleteSeatDocument);
  const [duplicateTable] = useMutation(DuplicateTableDocument);
  const [cloneSection] = useMutation(CloneSectionDocument);
  const [moveSeat] = useMutation(MoveSeatDocument);
  const [moveTable] = useMutation(MoveTableDocument);
  const [moveSection] = useMutation(MoveSectionDocument);
  const [autoGenerate] = useMutation(AutoGenerateSeatMapDocument);
  const [undoLayout] = useMutation(UndoLayoutDocument);
  const [redoLayout] = useMutation(RedoLayoutDocument);
  const [renameSection] = useMutation(RenameSectionDocument);
  const [renameTable] = useMutation(RenameTableDocument);

  const [editorMode, setEditorMode] = React.useState<EditorMode>("view");
  const [selectedItems, setSelectedItems] = React.useState<SelectedItem[]>([]);
  const [autoGenerateOpen, setAutoGenerateOpen] = React.useState(false);
  const [renameOpen, setRenameOpen] = React.useState(false);

  const [filters, setFilters] = React.useState<SeatMapFilters>({
    search: "",
    presence: "all",
  });

  const presenceMap = React.useMemo(() => {
    const map = new Map<string, NonNullable<SeatMapViewQuery["seatPresencesByEvent"]>[number]>();
    if (!mapData?.seatPresencesByEvent) {
      return map;
    }
    for (const p of mapData.seatPresencesByEvent) {
      map.set(p.seatId, p);
    }
    return map;
  }, [mapData]);

  const highlightedSeatIds = React.useMemo(() => {
    const searchTerm = filters.search.toLowerCase().trim();
    const hasSearch = searchTerm.length > 0;
    const hasPresenceFilter = filters.presence !== "all";

    if (!hasSearch && !hasPresenceFilter) {
      return undefined;
    }

    const result = new Set<string>();

    for (const s of seatList ?? []) {
      let match = true;

      if (hasSearch) {
        const holderName = getSeatHolderName(s.guestId ?? s.invitationId).toLowerCase();
        match =
          (s.number?.toString() ?? "").includes(searchTerm) ||
          (s.section.name ?? "").toLowerCase().includes(searchTerm) ||
          (s.table?.name ?? "").toLowerCase().includes(searchTerm) ||
          (s.label ?? "").toLowerCase().includes(searchTerm) ||
          holderName.includes(searchTerm);
      }

      if (match && hasPresenceFilter) {
        const p = presenceMap.get(s.id);
        switch (filters.presence) {
          case "free":
            match = !p && !s.guestId && !s.invitationId;
            break;
          case "occupied":
            match = Boolean(s.guestId) || Boolean(s.invitationId);
            break;
          case "INSIDE":
            match = p?.presenceState === ("INSIDE" as NonNullable<typeof p>["presenceState"]);
            break;
          case "revoked":
            match = p?.revoked === true;
            break;
        }
      }

      if (match) {
        result.add(s.id);
      }
    }

    return result;
  }, [filters, seatList, getSeatHolderName, presenceMap]);

  const ownSeatIds = React.useMemo(() => {
    if (!currentUser?.id || !seatList) {
      return new Set<string>();
    }
    return new Set(
      seatList
        .filter((s): s is typeof s & { guestId: string } => s.guestId === currentUser.id)
        .map((s) => s.id),
    );
  }, [currentUser, seatList]);

  const loading = seatListLoading || mapLoading;

  // ── Editor Actions ──

  const isAdmin = can(EventPermissionKey.ManageSeats);

  const handleModeToggle = () => {
    const next = editorMode === "view" ? "edit" : ("view" as EditorMode);
    setEditorMode(next);
    if (next === "view") {
      setSelectedItems([]);
    }
  };

  const handleAddSection = async () => {
    if (!mapData) {
      return;
    }
    const name = createDefaultSectionName(mapData.seatLayout);
    try {
      await createSection({
        variables: {
          input: { eventId, name, x: 50, y: 50, capacity: null, height: null, width: null, meta: null, order: null },
        },
      });
      await refetchMap();
      setSelectedItems([]);
    } catch (_err) {}
  };

  const handleAddTable = async () => {
    if (!mapData) {
      return;
    }
    const sections = mapData.seatLayout;
    if (sections.length === 0) {
      await handleAddSection();
      return;
    }
    const sectionSelection = selectedItems.find((s) => s.type === "section");
    const targetSectionId = sectionSelection?.id ?? sections[0]?.id;
    if (!targetSectionId) {
      return;
    }
    const section = sections.find((s) => s.id === targetSectionId);
    const tableName = createDefaultTableName(section?.tables ?? []);
    try {
      await createTable({
        variables: {
          input: {
            eventId,
            sectionId: targetSectionId,
            name: tableName,
            x: 100,
            y: 100,
            width: 100,
            height: 60,
            capacity: null,
            meta: null,
            order: null,
            rotation: null,
            shape: null,
          },
        },
      });
      await refetchMap();
      setSelectedItems([]);
    } catch (_err) {}
  };

  const handleDelete = async () => {
    if (selectedItems.length === 0) {
      return;
    }
    try {
      for (const item of selectedItems) {
        if (item.type === "section") {
          await deleteSection({ variables: { sectionId: item.id } });
        } else if (item.type === "table") {
          await deleteTable({ variables: { tableId: item.id } });
        } else if (item.type === "seat") {
          await deleteSeat({ variables: { seatId: item.id } });
        }
      }
      await refetchMap();
      setSelectedItems([]);
    } catch (_err) {}
  };

  const handleDuplicateTable = async () => {
    const table = selectedItems.find((s) => s.type === "table");
    if (!table || selectedItems.length !== 1) {
      return;
    }
    try {
      await duplicateTable({
        variables: {
          input: { tableId: table.id, offsetX: 60, offsetY: 60 },
        },
      });
      await refetchMap();
    } catch (_err) {}
  };

  const handleCloneSection = async () => {
    const section = selectedItems.find((s) => s.type === "section");
    if (!section || selectedItems.length !== 1) {
      return;
    }
    try {
      await cloneSection({
        variables: {
          input: { sectionId: section.id, offsetX: 100, offsetY: 100 },
        },
      });
      await refetchMap();
    } catch (_err) {}
  };

  const handleAutoGenerate = async (input: {
    sectionName: string;
    seatCount: number;
    tableCount: number;
    tableShape: TableShape;
    sectionLayout: SectionShape;
    spacing: number;
  }) => {
    try {
      await autoGenerate({ variables: { input: { eventId, ...input } } });
      await refetchMap();
      setAutoGenerateOpen(false);
    } catch (_err) {}
  };

  const handleMoveSeat = async (seatId: string, x: number, y: number) => {
    try {
      await moveSeat({ variables: { input: { id: seatId, x, y, rotation: null } } });
    } catch (_err) {}
  };

  const handleMoveTable = async (tableId: string, x: number, y: number) => {
    try {
      await moveTable({ variables: { input: { id: tableId, x, y } } });
    } catch (_err) {}
  };

  const handleMoveSection = async (sectionId: string, x: number, y: number) => {
    try {
      await moveSection({ variables: { input: { id: sectionId, x, y } } });
    } catch (_err) {}
  };

  const handleUndo = async () => {
    try {
      await undoLayout({ variables: { eventId } });
      await refetchMap();
    } catch (_err) {}
  };

  const handleRedo = async () => {
    try {
      await redoLayout({ variables: { eventId } });
      await refetchMap();
    } catch (_err) {}
  };

  const handleRename = async (
    updates: { id: string; type: SelectedItem["type"]; newName: string }[],
  ) => {
    try {
      for (const u of updates) {
        if (u.type === "section") {
          await renameSection({ variables: { input: { sectionId: u.id, newName: u.newName } } });
        } else if (u.type === "table") {
          await renameTable({ variables: { input: { tableId: u.id, newName: u.newName } } });
        }
      }
      await refetchMap();
    } catch (_err) {}
  };

  return (
    <RouteGuard featureId="seat-map">
    <Stack spacing={1} sx={{ height: "100dvh", overflow: "hidden", position: "relative" }}>
      <Box
        sx={{
          position: "absolute",
          top: 0,
          left: 0,
          right: 0,
          zIndex: 50,
          px: { xs: 1.5, md: 3 },
          py: 1,
          bgcolor: (theme) => alpha(theme.palette.background.default, 0.7),
          backdropFilter: "blur(16px)",
          borderBottom: (theme) => `1px solid ${alpha(theme.palette.divider, 0.12)}`,
          display: "flex",
          flexDirection: "column",
          gap: 1,
        }}
      >
        <Box sx={{ display: "flex", alignItems: "center", gap: 1.5 }}>
          <BackToEventDetailButton />
          <Typography variant="subtitle1" sx={{ fontWeight: 700, flexGrow: 1 }}>
            Sitzplan
          </Typography>
          <Stack direction="row" spacing={0.5} sx={{ alignItems: "center" }}>
            <Chip size="small" label="frei" sx={{ bgcolor: "grey.900", color: "grey.100" }} />
            <Chip size="small" label="belegt" color="error" />
            <Chip size="small" label="eingecheckt" color="info" />
            <SeatColorLegend colorGroups={seatColorGroups} />
          </Stack>
        </Box>

        <SeatMapSearch
          filters={filters}
          onChange={(v) => setFilters(v)}
          {...(highlightedSeatIds ? { resultCount: highlightedSeatIds.size } : {})}
        />
      </Box>

      {isAdmin && (
        <SeatMapEditorToolbar
          mode={editorMode}
          onModeToggle={handleModeToggle}
          selectedItems={selectedItems}
          onAddSection={handleAddSection}
          onAddTable={handleAddTable}
          onDelete={handleDelete}
          onDuplicateTable={handleDuplicateTable}
          onCloneSection={handleCloneSection}
          onAutoGenerate={() => setAutoGenerateOpen(true)}
          onRename={() => setRenameOpen(true)}
          onUndo={handleUndo}
          onRedo={handleRedo}
        />
      )}

      <SeatMapCanvas
        sections={mapData?.seatLayout ?? []}
        presenceMap={presenceMap}
        seats={seats}
        seatGuestMap={seatGuestMap}
        getSeatHolderLabel={getSeatHolderLabel}
        loading={loading}
        eventId={eventId}
        role={activeRole ?? "GUEST"}
        highlightedSeatIds={highlightedSeatIds}
        ownSeatIds={ownSeatIds}
        isEditing={editorMode === "edit"}
        selectedItems={selectedItems}
        onSelectItem={setSelectedItems}
        onMoveSeat={handleMoveSeat}
        onMoveTable={handleMoveTable}
        onMoveSection={handleMoveSection}
      />

      <SeatMapAutoGenerateDialog
        open={autoGenerateOpen}
        onClose={() => setAutoGenerateOpen(false)}
        onGenerate={handleAutoGenerate}
      />

      <SeatMapRenameDialog
        open={renameOpen}
        selectedItems={selectedItems}
        onClose={() => setRenameOpen(false)}
        onRename={handleRename}
      />
    </Stack>
    </RouteGuard>
  );
}
