"use client";

import React, { useState } from "react";
import { Badge, IconButton, Popover, Box, Stack, Typography, Button, useTheme, alpha } from "@mui/material";
import MailRoundedIcon from "@mui/icons-material/MailRounded";
import ContentCopyRoundedIcon from "@mui/icons-material/ContentCopyRounded";
import { InvitationLogic } from "@/checkpoint/hooks/invitation/useInvitationLogic";

/**
 * Inbox button + panel that displays newly created users.
 * Each entry contains username/password generated by the Auth service.
 * Works for both single and bulk approve flows.
 */
export default function UserCreationInbox({ logic }: { logic: InvitationLogic }) {
  const [anchorEl, setAnchorEl] = useState(null);
    const theme = useTheme();
  

  const open = Boolean(anchorEl);
  const { createdUsers, unreadCount, resetUserInbox } = logic;

  const handleOpen = (e: any) => setAnchorEl(e.currentTarget);
  const handleClose = () => setAnchorEl(null);

  return (
    <>
      {/* Button with badge */}
      <Badge color="primary" badgeContent={unreadCount} invisible={unreadCount === 0}>
        <IconButton
          onClick={handleOpen}
          sx={{
                    backdropFilter: "blur(12px)",
                    background: alpha(theme.palette.primary.main, 0.15),
                    border: `1px solid ${alpha(theme.palette.primary.main, 0.3)}`,
                    boxShadow: theme.shadows[3],
                    "&:hover": {
                      background: alpha(theme.palette.primary.main, 0.25),
                    },
          }}
        >
          <MailRoundedIcon />
        </IconButton>
      </Badge>

      {/* Popover panel */}
      <Popover
        open={open}
        anchorEl={anchorEl}
        onClose={handleClose}
        anchorOrigin={{
          vertical: "bottom",
          horizontal: "right",
        }}
        slotProps={{
          paper: {
            sx: {
              p: 2,
              borderRadius: "18px",
              width: 340,
              background: "rgba(255,255,255,0.55)",
              backdropFilter: "blur(18px)",
              boxShadow: "inset 0 0 0 1px rgba(255,255,255,0.4), 0 12px 40px rgba(0,0,0,0.2)",
            },
          },
        }}
      >
        <Stack spacing={2}>
          <Stack
            direction="row"
            sx={{
              justifyContent: "space-between",
            }}
          >
            <Typography
              variant="h6"
              sx={{
                fontWeight: 700,
                fontSize: 12,
              }}
            >
              Neue Benutzer
            </Typography>

            <Button size="small" onClick={resetUserInbox}>
              Löschen
            </Button>
          </Stack>

          {createdUsers.length === 0 && (
            <Typography sx={{ opacity: 0.6 }}>Keine neuen Benutzer</Typography>
          )}

          <Stack spacing={1.5} sx={{ maxHeight: 300, overflowY: "auto" }}>
            {createdUsers.map((u, index) => (
              <Box
                key={index}
                sx={{
                  p: 1.4,
                  borderRadius: "14px",
                  background: "rgba(255,255,255,0.4)",
                  border: "1px solid rgba(255,255,255,0.3)",
                  backdropFilter: "blur(10px)",
                }}
              >
                <Typography>
                  {u.lastName} {u.firstName}
                </Typography>
                <Typography
                  sx={{
                    fontWeight: 600,
                    fontSize: 12,
                  }}
                >
                  Einladung: {u.invitationId}
                </Typography>
                <Typography>Username: {u.username}</Typography>
                <Typography>Passwort: {u.password}</Typography>

                <IconButton
                  size="small"
                  onClick={() => navigator.clipboard.writeText(`${u.username} / ${u.password}`)}
                >
                  <ContentCopyRoundedIcon fontSize="small" />
                </IconButton>
              </Box>
            ))}
          </Stack>
        </Stack>
      </Popover>
    </>
  );
}
