query GetFullEventInvitation($eventIds: [ID!]!) {
  getFullByEventIds(eventIds: $eventIds) {
    ...InvitationFull
  }
}

query GetGlobalEventInvitationList($eventIds: [ID!]!) {
  getFullByEventIds(eventIds: $eventIds) {
    id
    eventId
    eventName
    eventEndsAt
    type
    status
    firstName
    lastName
    email
    phoneNumber
    phoneNumbers {
      countryCode
      number
      type
      label
      isPrimary
    }
    maxInvitees
    invitedByInvitationId
    rsvpChoice
    plusOneAgeCategory
  }
}
