# import InvitationFull from "../fragments/invitation.fragment.graphql"

query Invitation($invitationId: ID!) {
  invitation(id: $invitationId) {
    ...InvitationFull
  }
}

query GetInvitation($invitationId: ID!) {
  invitation(id: $invitationId) {
    id
    status
    eventId
    eventName
    eventEndsAt

    firstName
    lastName
    email

    phoneNumbers {
      countryCode
      number
      type
      label
      isPrimary
    }

    approvedAt
    guestNote
    selectedInvitedBy
    plusOneAgeCategory
    plusOnes {
      id

      lastName
      firstName
      email
      plusOneAgeCategory
      guestNote
      selectedInvitedBy
      phoneNumbers {
        countryCode
        number
        type
        label
        isPrimary
      }
    }
  }
}

query PlusOneInvitations($invitationId: ID!) {
  invitation(id: $invitationId) {
    id
    plusOnes {
      id
      firstName
      lastName
      email
      status
      plusOneAgeCategory
      phoneNumbers {
        countryCode
        number
        type
        label
        isPrimary
      }
    }
    maxInvitees
  }
}
